### ISSUE TITLE
ハイフンに変換しておく前処理

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#27]

**Comment by tanimuranaomichi** [comment]
薬局のハイフンぽい文字
‐

**Comment by kaizumaki** [comment]
「ハイフンっぽいもの問題」は、先人の知恵がたんまりあるので...大いに活用するのがよいかと思います 😄 
このあたりとか↓
[ハイフンに似た文字 | Tech控え帳](https://www.chihayafuru.jp/tech/index.php/archives/2469)
[Unicodeにあるハイフン/マイナス/長音符/波線/チルダのコレクション | hydroculのメモ](https://hydrocul.github.io/wiki/blog/2014/1101-hyphen-minus-wave-tilde.html)

どこかにAPIとかないのかな 🤔

**Comment by Tom177** [comment]
https://qiita.com/non-caffeine/items/77360dda05c8ce510084
上記でプログラムに組み込んでみます

**Comment by To-Ki-O** [comment]
以下の`Commit`にて対応済み
eddef2fbed2f153a282e6ed23cbaca3cfc3f674e
