### ISSUE TITLE
カラム名の全県統一化

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#28]
都道府県ごとのcsv、カラム名が若干ことなる場合があるため、突き合わせるのにやや手間取る。(ex. 診療時間のカラム名)

* 医療機関における緊急避妊に係る対面診療への対応可能時間帯
  * 北海道
  * 神奈川県

* 医療機関における緊急避妊への対応可能時間帯
  * 滋賀県
  * 千葉県
  * 栃木県

* 医療機関における緊急避妊への対応可能時間帯(祝日のある週は診療日が異なる可能性がありますので事前に対応可能か電話で確認することをおすすめします。)
  * 愛知県

* 医療機関における緊急避妊にかかる対面診療への対応可能時間帯
  * そのほか全ての都府県

**Comment by hello112334** [comment]
#31 #11 フォマードファイルを作って、順番+同じ名前で出力できる機能を入れてみると思います
