### ISSUE TITLE
市区町村列の追加

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#3]
* 郵便番号から市区町村名を取得する
* 市区町村名の列を追加する

**Comment by kaizumaki** [comment]
> * 郵便番号から市区町村名を取得する

こちらちょっとググったのですが、難しそうですね。。郵便番号から市区町村が一意に決まらないことがあるのだとか。

以下参考
- https://github.com/geolonia/japanese-addresses/issues/9
- [郵便番号や市区町村データを取り扱うときにはまったこと](https://qiita.com/_takwat/items/3a121656425fac7bb820)

ジオコーダー的なことはgeoloniaさんが国内ではトップだと思うのですが、ほかに使えそうなAPIなど心当たりありますか...？

**Comment by To-Ki-O** [comment]
アフターピル検索さんのPJでは、どのように変換されているか聞いてみています！

**Comment by kaizumaki** [comment]
一意に決まらないことをどっかで妥協するとしたら、こちら↓のAPIを使うのが良さそうです。
https://github.com/madefor/postal-code-api

**Comment by kaizumaki** [comment]
> 一意に決まらないことをどっかで妥協するとしたら、こちら↓のAPIを使うのが良さそうです。 https://github.com/madefor/postal-code-api

こちらで着手してみますね！

**Comment by kaizumaki** [comment]
@To-Ki-O @ryo-ma こちらのissue、いったん私のアサインをはずしてもらってもいいでしょうか 😅 
以下の観点から検討いただきたく、いったんお返ししたいなと思いまして。
- 1行ずつの照合・要素追加の処理のロジックが初めて発生していると思うのですが、いまある処理のどの段階で1行ずつの処理を挟み込むかを検討してもらいたい
- 今後も同様の1行ずつの処理が発生すると思うので、ほどよくメソッド分割していくことを検討してもらいたい

それと私がpandasにあまり慣れていないこともあり、結構沼が深いので 😅 このまま私の方で進めないほうがいいなと思いました。

**Comment by hello112334** [comment]
試しに郵便局が提供している郵便番号のデータセットで変換してみましたが、記載されていない番号がありました（謎）。
正規表現で住所から切り分けたらどうでしょうか。

・郵便局のデータセット
https://www.post.japanpost.jp/zipcode/download.html

**Comment by To-Ki-O** [comment]
@hello112334 さん
ありがとうございます。
記載されていないところがあるのですね。。

そうですね。
その方針でお願いいたします。
