### ISSUE TITLE
個別事業所の郵便番号から都道府県名・市区町村名を取得する

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#33]
郵便局が公開している以下の個別事業所のデータから都道府県名と市区町村名を取得する
1. dimを使って以下のデータを取得する
  `https://www.post.japanpost.jp/zipcode/dl/jigyosyo/index-zip.html`
2. 医療機関データと上記のデータで、郵便番号をキーとして突き合わせを行う

**Comment by nichesuch** [comment]
実際のzipは以下
https://www.post.japanpost.jp/zipcode/dl/jigyosyo/zip/jigyosyo.zip

dimで持ってきて、unzip utf-8に変換

**Comment by nichesuch** [comment]
UTF-8への変更がうまくdimでできない...

**Comment by nichesuch** [comment]
怪しげな文字が使われているかららしい
codecsで怪しげな文字は無視して変換してしまう。

**Comment by nichesuch** [comment]
jigyosyoのcsvのカラムの順番がken_allと違うので、合わせて結合して使う
