### ISSUE TITLE
郵便番号から都道府県名と市区町村名を取得できなかった場合の処理

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#35]
現状は以下のフローになっています。
1. `ken_all.csv`と医療機関データで郵便番号をキーとして突き合わせを行う
2. 個別事業所データと医療機関データで郵便番号をキーとして突き合わせを行う
3. 住所から都道府県名と市区町村名を取得する

以下のフローに変更したいと考えています。
1. `ken_all.csv`と医療機関データで郵便番号をキーとして突き合わせを行う
2. 個別事業所データと医療機関データで郵便番号をキーとして突き合わせを行う
3. `エラー`列(String列挙)を作成し、`郵便番号`という文字列を追加する

**Comment by hello112334** [comment]
#33 と合わせて変更が必要ですので修正中
