### ISSUE TITLE
URLのバリデーション

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#37]
以下の手順で有効なURLであるかを確認したいと考えています。
1. URLに`Ping`を打ち、`404`などのエラーが返ってこないかを確認する
2. エラーが返ってきた行の`産科、婦人科又は産婦人科の標榜の有無`のカラム内に`p`や`m`が入り込んでいないか確認する
  ※ PDFを読み取る際に次のカラムに入り込んでしまっていることがあるためです。
3. `エラー`列(String列挙)を追加し、2番の手順で引っ掛かっている場合は`URL(読み取り)`をそうでない場合は`URL(リンク切れ)`の文字列を追記する

**Comment by hello112334** [comment]
URLはHPのURL（連絡先_FormURL）でしょうか？

**Comment by To-Ki-O** [comment]
@hello112334 さん
はい、`URL`は`連絡先_FormURL`のことを指しています。

**Comment by To-Ki-O** [comment]
以下の`Commit`で対応済み

a7b0c0ca530f5caf048fd6349367997ea79bed92
