### ISSUE TITLE
緯度経度のバリデーション

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#38]
緯度経度が大きくずれていないかを確認したいと考えています。

Step 1
① Google API で住所から緯度経度を取得する
② 返却値がない場合や2値以上の返却値がある場合は、`エラー`列(String列挙)を作成し、`緯度経度(Googleエラー)`の文字列を追記する

Step2
① 東京大学空間情報科学研究センターから取得した緯度経度とGoogle APIの緯度経度を比較する
  ※ 完全な一致ではなく、小数点何桁までの一致とするかは要検討
② 一致しない場合は`エラー`列(String列挙)を作成し、`緯度経度(不一致)`の文字列を追記する

**Comment by hello112334** [comment]
緯度経度とGoogle APIの緯度経度を比較すると、アクセスキーの申請やAPI料金がかかるところがあるため、
緯度経度が大きくずれていないかを都道府県に該当するかどうかで判定するのはいかがでしょうか。
⇒ 日本の都道府県を表すgeojsonで緯度経度を判定し、一致しているかどうかを確認する

・国土数値情報ダウンロードサイト
https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N03-2024.html

・Google Geocoding API の使用量と請求額について
https://developers.google.com/maps/documentation/geocoding/usage-and-billing?hl=ja

**Comment by hello112334** [comment]
一致しない場合については下記のようにまとめたことを考えています。
```
# エラーリスト
class ERROR_LIST(Enum):
    POST_CODE = "郵便番号"
    # 個別事業所データと医療機関データに郵便番号がない

    LAT_LON_ERROR = "緯度経度(検索エラー)"
    # 緯度経度でgeojsonから都道府県を抽出した際に、空欄になったのか郵便番号から都道府県名と比較して不一致

    LAT_LON_MISMATCH = "緯度経度(不一致)" 
    # センターから取得した緯度経度とGoogle APIの緯度経度と比較し、合わない

    GOOGLE_LAT_LON_ERROR = "緯度経度(Googleエラー)"  
    # Google APIで緯度経度を取得する際、返却値がない場合や2値以上の返却値がある

    URL_READ  = "URL(読み取り)" 
    # 産科、婦人科又は産婦人科の標榜の有無のカラム内にpやmが入り込んでいる(?)

    URL_EXPIRED = "URL(リンク切れ)"
    # URLにPingを打ち、404などのエラーが返った
 ```

**Comment by To-Ki-O** [comment]
ご検討と調査いただき、ありがとうございます！
先週、ご提案いただいた方法で良いかなと感じています。
お金がかかってしまうとOSSとしては、あまりよくないかと思っていますので。。
