### ISSUE TITLE
緯度経度列の追加

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#4]
* 住所から緯度経度を取得する
* 緯度経度列を追加する

※参考→[デジタル庁公開のGeoCoder](https://github.com/digital-go-jp/abr-geocoder)

**Comment by kaizumaki** [comment]
デジタル庁でGeoCoderを公開しているのですね 👀 
Geoloniaさんのこちら↓だとAPIで取得できるのでよさそうなのですが、どうでしょう？
https://github.com/geolonia/community-geocoder

**Comment by ryo-ma** [comment]
このAPIはJSのHTMLから読み込む感じなのですよね。jsonとかでAPI叩けたらよかったのですが。
```javascript
<script src="https://cdn.geolonia.com/community-geocoder.js"></script>
```

**Comment by hello112334** [comment]
東京大学空間情報科学研究センターが提供している「CSVアドレスマッチングサービス」では、住所から緯度経度を取得できますが、いかがでしょうか。

・概要
https://geocode.csis.u-tokyo.ac.jp/home/csv-admatch/#tutorial

・Pythonパッケージ名
jageocoder

![image](https://github.com/c-3lab/opendata-pdf-to-csv/assets/37241401/d67a28ce-7ff8-46fa-8155-b10b1d09b8df)

**Comment by hello112334** [comment]
URLを利用して緯度経度を取得する際、アクセス数が多いとtoken failedエラーが発生する可能性があります。そのため、エラーが発生した場合には、自動的にPythonのパッケージに切り替えるように対応しました。
