### ISSUE TITLE
市区町村コード列の追加

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#5]
#3 実装後に対応する必要がある

* 市区町村列から市区町村コードを取得する
* 市区町村コード列を追加する

**Comment by To-Ki-O** [comment]
https://www.soumu.go.jp/denshijiti/code.html

https://www.j-lis.go.jp/spd/code-address/jititai-code.html

6ケタとした方が良い

**Comment by To-Ki-O** [comment]
現状は`ken_all`から取得してきた5桁の市区町村コードを入れている。

**Comment by To-Ki-O** [comment]
`ken_all`の記述とマッチしない場合がある
(例) 新潟市

**Comment by To-Ki-O** [comment]
郵便番号の記載がない個別の事業所は以下のデータをdimで取得して、突き合わせを行う
https://www.post.japanpost.jp/zipcode/dl/jigyosyo/index-zip.html

**Comment by To-Ki-O** [comment]
6桁の市区町村コードにしたい
最後の桁はパリティチェック用の数字なので、計算してしまっても良いかもしれない

**Comment by hello112334** [comment]
総務省のサイトに掲載している「全国地方公共団体コード仕様」
この通りで計算すればいいでしょうかね。

![image](https://github.com/user-attachments/assets/eb6a948a-e226-436f-a5dd-d5bb62877171)

**Comment by To-Ki-O** [comment]
はい、それでお願いします！
