### ISSUE TITLE
ファイル名の変更

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#6]
* 現在は以下のような命名
  * (dimでの管理順番)_(都道府県名).csv 
    * 例：01_北海道.csv

* 以下のような形の方がよりわかりやすいと考えられる
  * (都道府県番号)_(都道府県名)_(更新日時).csv
    * 例：01_Hokkaidou_20240315.csv

**Comment by RyNtake** [comment]
こちらのIssue着手します

**Comment by RyNtake** [comment]
READM.mdについて、「## 手動で実行」の手順4を
```
dim install
```
に変更しておきます。
