### ISSUE TITLE
自由記述欄の改行コードをエスケープする

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/opendata-pdf-to-csv#7]
現在は全ての改行コードを消しているが、
自由記述欄の改行コードについては消さずにケスケープ処理を行う必要がある

**Comment by ryosuke-betw** [comment]
こちらのIssueについて着手します。

**Comment by To-Ki-O** [comment]
以下のPRにより、本Issueが解決したため、クローズとする。
https://github.com/c-3lab/opendata-pdf-to-csv/pull/25
